1.	Create a 2D array and print the dim and shape

In [3]:
import pandas as pd
import numpy as np

In [2]:
s = np.array([[1,2,3]])
s

array([[1, 2, 3]])

In [3]:
s.ndim

2

2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [4]:
v = np.arange(20)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
h = v[10:16]
print(h)

[10 11 12 13 14 15]


3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [6]:
a = np.array([[1,2,4,5,6],[2,4,5,7,7],[4,5,6,7,8],[4,7,2,4,7],[3,6,4,5,1],[3,5,4,6,2],[4,5,6,2,6]])
b = np.array([[2,4,5,7,1],[3,5,2,3,7],[4,7,8,4,5],[5,7,6,8,6],[3,4,6,5,7],[5,8,9,7,5],[5,7,4,3,6]])
print(a+b)

[[ 3  6  9 12  7]
 [ 5  9  7 10 14]
 [ 8 12 14 11 13]
 [ 9 14  8 12 13]
 [ 6 10 10 10  8]
 [ 8 13 13 13  7]
 [ 9 12 10  5 12]]


In [7]:
print(a-b)

[[-1 -2 -1 -2  5]
 [-1 -1  3  4  0]
 [ 0 -2 -2  3  3]
 [-1  0 -4 -4  1]
 [ 0  2 -2  0 -6]
 [-2 -3 -5 -1 -3]
 [-1 -2  2 -1  0]]


In [8]:
print(a*b)

[[ 2  8 20 35  6]
 [ 6 20 10 21 49]
 [16 35 48 28 40]
 [20 49 12 32 42]
 [ 9 24 24 25  7]
 [15 40 36 42 10]
 [20 35 24  6 36]]


In [9]:
print(a/b)

[[0.5        0.5        0.8        0.71428571 6.        ]
 [0.66666667 0.8        2.5        2.33333333 1.        ]
 [1.         0.71428571 0.75       1.75       1.6       ]
 [0.8        1.         0.33333333 0.5        1.16666667]
 [1.         1.5        0.66666667 1.         0.14285714]
 [0.6        0.625      0.44444444 0.85714286 0.4       ]
 [0.8        0.71428571 1.5        0.66666667 1.        ]]


4.	Create 2 incompatible arrays for broadcast and print out the error

In [10]:
q = np.array([1,2,3,4])
w = np.array([1,2,3])
print(q+w)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

5.	Create two arrays of any dimension and perform vstack and hstack

In [ ]:
e= np.array([2,4,6])
r = np.array([5,6,8])

In [ ]:
np.hstack((e,r))

In [ ]:
np.vstack((e,r))

6.	Append two arrays using axis = 0 and axis = 1

In [ ]:
t = np.array([[1,2,3],[3,6,9]])
np.append(t,[[4,5,6],[8,9,1]])

In [ ]:
np.append(t,[[4,5,6],[8,9,1]],axis=1)

In [ ]:
np.append(t,[[4,5,6],[8,9,1]],axis=0)

7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [15]:
df = [["hari",25,"pass",45],['ajay',26,"fail",24],['jeeva',27,"pass",67],["jimili",28,"pass",84],['dinh',29,"fail",20],
      ['steven',30,"pass",40],['analise',31,"pass",45],['mellisa',32,"fail",90]]
f =pd.DataFrame(df,columns=["name","roll number","pass/fail","percentage"])
f

name  roll number pass/fail  percentage
0     hari           25      pass          45
1     ajay           26      fail          24
2    jeeva           27      pass          67
3   jimili           28      pass          84
4     dinh           29      fail          20
5   steven           30      pass          40
6  analise           31      pass          45
7  mellisa           32      fail          90

8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [52]:
df1 = {"name":["hari","ajay","jimili","steven"],"roll number":[25,26,27,28],"pass/fail":["pass","fail","pass","fail"],
    "percentage":[25,67,89,90],"area":["anna nagar","koyembedu","valasaravakkam","chetpet"],"transport":["bus","car","bus","bike"],
    "arrears":[0,3,5,0],"college":["REC","VIT","RIT","SVCE"]}
g = pd.DataFrame(df1)
g

name  roll number pass/fail  percentage            area transport  \
0    hari           25      pass          25      anna nagar       bus   
1    ajay           26      fail          67       koyembedu       car   
2  jimili           27      pass          89  valasaravakkam       bus   
3  steven           28      fail          90         chetpet      bike   

   arrears college  
0        0     REC  
1        3     VIT  
2        5     RIT  
3        0    SVCE

9.	Use loc and ilocto subset the data for the above dataframe

In [53]:
g.loc[0:2]

name  roll number pass/fail  percentage            area transport  \
0    hari           25      pass          25      anna nagar       bus   
1    ajay           26      fail          67       koyembedu       car   
2  jimili           27      pass          89  valasaravakkam       bus   

   arrears college  
0        0     REC  
1        3     VIT  
2        5     RIT

In [54]:
g.iloc[0:3]

name  roll number pass/fail  percentage            area transport  \
0    hari           25      pass          25      anna nagar       bus   
1    ajay           26      fail          67       koyembedu       car   
2  jimili           27      pass          89  valasaravakkam       bus   

   arrears college  
0        0     REC  
1        3     VIT  
2        5     RIT

10.	How to check the total number of not null values in a column?

In [55]:
df2 = pd.Series({'One':np.NaN, 'Two':np.NaN, 'Three':np.NaN})
df2

One     NaN
Two     NaN
Three   NaN
dtype: float64

In [56]:
df2.isnull().sum()

3

11.	Create a dataframe with missing values and fill them all with 100

In [22]:
i = [['one',13,np.NaN],['two',14,np.NaN]]
z = pd.DataFrame(i,columns=['num','count','value'])
z

num  count  value
0  one     13    NaN
1  two     14    NaN

In [25]:
z.fillna(100)

num  count  value
0  one     13  100.0
1  two     14  100.0

12.	Create a dataframe with missing values and drop the null records

In [30]:
o = [['one',13,np.NaN],['two',15,100],['two',14,np.NaN]]
z= pd.DataFrame(o)
z

0   1      2
0  one  13    NaN
1  two  15  100.0
2  two  14    NaN

In [31]:
z.dropna()

0   1      2
1  two  15  100.0

13.	Perform following aggregation task on below table

a.	Get the average age group by Regrion

b.	Get the sum of Age and Validation group by Hair color and then reset the index

c.	Get the man and the median of Age group by Region


In [4]:
df2 = ({ 'Age' :  [25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23] ,
 'Hair Color' :  [ 'Black' , 'Black' , 'Red' , 'Blond' , 'Brown' , 'Brown' , 'Black' , 'Brown' , 'Blond' , 'Blond' , 'Black' , 'Black' , 'Brown' , 'Black' , 'Blond' , 'Black' , 'Brown' ] ,
 'U.S. Region' :  [ 'Southwest' , 'Northwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southeast' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southeast' , 'Southeast' , 'Northwest' , 'Southeast' ] ,
 'Validation' :  [1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1] 
})
x = pd.DataFrame(df2)
x

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [14]:
x.groupby(["U.S. Region"])['Age'].mean()   ##a. Get the average age group by Regrion

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [19]:
x.groupby(['Hair Color'])['Age','Validation'].sum().reset_index() ##b. Get the sum of Age and Validation group by Hair color and then reset the index

C:\Users\Srivatsa\AppData\Local\Temp/ipykernel_28016/2927216136.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  x.groupby(['Hair Color'])['Age','Validation'].sum().reset_index()                   ##b. Get the sum of Age and Validation group by Hair color and then reset the index


Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [27]:
x.groupby(['U.S. Region'])['Age'].agg([np.mean,np.median])              ##c. Get the man and the median of Age group by Region

mean  median
U.S. Region                   
Northeast    32.750000    31.0
Northwest    40.500000    40.5
Southeast    31.000000    25.5
Southwest    29.857143    25.0

## 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [35]:
s_left=x.loc[0:8]
s_right =x.loc[9:]

In [36]:
s_left

Age Hair Color U.S. Region  Validation
0   25      Black   Southwest           1
1   30      Black   Northwest           1
2   45        Red   Northeast           1
3   35      Blond   Southwest           0
4   33      Brown   Southwest           0
5   35      Brown   Northeast           0
6   25      Black   Southwest           0
7   52      Brown   Southeast           0
8   21      Blond   Southwest           1

In [37]:
s_right

Age Hair Color U.S. Region  Validation
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [39]:
##merge

pd.merge(s_left,s_right,on='U.S. Region')


Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      35        Blond   Southwest             0     48        Black   
3      35        Blond   Southwest             0     22        Black   
4      33        Brown   Southwest             0     48        Black   
5      33        Brown   Southwest             0     22        Black   
6      25        Black   Southwest             0     48        Black   
7      25        Black   Southwest             0     22        Black   
8      21        Blond   Southwest             1     48        Black   
9      21        Blond   Southwest             1     22        Black   
10     30        Black   Northwest             1     51        Black   
11     45          Red   Northeast             1     24        Blond   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     24        Blond   
14     35        Brown   Northeast             0     27        Brown   
15     52        Brown   Southeast             0     28        Black   
16     52        Brown   Southeast             0     21        Blond   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

In [40]:
#left join

s_left.merge(s_right, on='U.S. Region',how = 'left')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      30        Black   Northwest             1     51        Black   
3      45          Red   Northeast             1     24        Blond   
4      45          Red   Northeast             1     27        Brown   
5      35        Blond   Southwest             0     48        Black   
6      35        Blond   Southwest             0     22        Black   
7      33        Brown   Southwest             0     48        Black   
8      33        Brown   Southwest             0     22        Black   
9      35        Brown   Northeast             0     24        Blond   
10     35        Brown   Northeast             0     27        Brown   
11     25        Black   Southwest             0     48        Black   
12     25        Black   Southwest             0     22        Black   
13     52        Brown   Southeast             0     28        Black   
14     52        Brown   Southeast             0     21        Blond   
15     52        Brown   Southeast             0     23        Brown   
16     21        Blond   Southwest             1     48        Black   
17     21        Blond   Southwest             1     22        Black   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             0  
13             1  
14             1  
15             1  
16             1  
17             0

In [42]:
#outer join

s_left.merge(s_right, on='U.S. Region',how = 'right')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      45          Red   Northeast             1     24        Blond   
1      35        Brown   Northeast             0     24        Blond   
2      25        Black   Southwest             1     48        Black   
3      35        Blond   Southwest             0     48        Black   
4      33        Brown   Southwest             0     48        Black   
5      25        Black   Southwest             0     48        Black   
6      21        Blond   Southwest             1     48        Black   
7      25        Black   Southwest             1     22        Black   
8      35        Blond   Southwest             0     22        Black   
9      33        Brown   Southwest             0     22        Black   
10     25        Black   Southwest             0     22        Black   
11     21        Blond   Southwest             1     22        Black   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     27        Brown   
14     52        Brown   Southeast             0     28        Black   
15     52        Brown   Southeast             0     21        Blond   
16     30        Black   Northwest             1     51        Black   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              0  
1              0  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1

15.	Split the below table and perform concat row wise and column wise

In [47]:
pd.concat([s_left,s_right],axis=0)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [48]:
pd.concat([s_left,s_right],axis=1)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   25.0      Black   Southwest         1.0   NaN        NaN         NaN   
1   30.0      Black   Northwest         1.0   NaN        NaN         NaN   
2   45.0        Red   Northeast         1.0   NaN        NaN         NaN   
3   35.0      Blond   Southwest         0.0   NaN        NaN         NaN   
4   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
5   35.0      Brown   Northeast         0.0   NaN        NaN         NaN   
6   25.0      Black   Southwest         0.0   NaN        NaN         NaN   
7   52.0      Brown   Southeast         0.0   NaN        NaN         NaN   
8   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
9    NaN        NaN         NaN         NaN  24.0      Blond   Northeast   
10   NaN        NaN         NaN         NaN  48.0      Black   Southwest   
11   NaN        NaN         NaN         NaN  22.0      Black   Southwest   
12   NaN        NaN         NaN         NaN  27.0      Brown   Northeast   
13   NaN        NaN         NaN         NaN  28.0      Black   Southeast   
14   NaN        NaN         NaN         NaN  21.0      Blond   Southeast   
15   NaN        NaN         NaN         NaN  51.0      Black   Northwest   
16   NaN        NaN         NaN         NaN  23.0      Brown   Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0